//
//		Lab 4-3
//
//		Maintain name and balance information in a map
//
#include <iostream>
#include <string>
#include <map>
using namespace std;

int main()
{

	string name;
	double amount;

	// TODO
	// Declare a map to store pairs of names and amounts.

	// TODO
	// Create a loop to read in names and amounts.
	// Store each pair in the map, with the name as the key
	// and the amount as the value.

	// TODO
	// Declare a map iterator. Use it in a loop thats
	// prints out all the name and amount pairs in the map.

	// TODO
	// Create a loop to read in names and look up the
	// corresponding amount

	return 0;
}

